### ISSUE TITLE
"Unexpected character encountered while parsing value: C. Path '', line 0, position 0" after install on 7.12.1

### ISSUE THREAD

**Issue by johnseto** [prjseal/CodeShareUmbracoStarterKit#2]
Happens on fresh install of Umbraco 7.12.1 (from the package catalogue via backoffice). Error below. Looking at the Metadata field, looks like this, I assume the tags aren't meant to split like this. 

![image](https://user-images.githubusercontent.com/4864638/45286012-90350a00-b4dc-11e8-8cc6-299ae17a9d8c.png)

_Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 0, position 0._

```
Line 3:  @using Umbraco.Web.Models
Line 4:  
Line 5:  <title>@Umbraco.Field("metaName", altFieldAlias: "pageName")</title>
```

**Comment by prjseal** [comment]
Thanks John
It looks like some recent changes to Umbraco have broken it. I’ll have to get on to fixing it.

**Comment by johnseto** [comment]
If i get time today, I'll see if it works on 7.12.2

**Comment by prjseal** [comment]
This was due to a change submitted by Jan which stores the tags data as json by default. I’ve fixed the package now and it works again.

**Comment by johnseto** [comment]
Thanks Paul. Works now!
